package ca.powerj;

import java.util.Calendar;

class OCasePending {
	boolean update = false;
	boolean cancel = false;
	byte turID = 0;
	byte statusID = 0;
	byte subID = 0;
	byte spyID = 0;
	byte procID = 0;
	byte noSpec = 0;
	short facID = 0;
	short grossID = 0;
	short embedID = 0;
	short microID = 0;
	short routeID = 0;
	short finalID = 0;
	short noBlocks = 0;
	short noSlides = 0;
	short mainBlks = 0;
	short mainSpec = 0;
	short cutoff = 0;
	short passed = 0;
	short delay = 0;
	short grossTAT = 0;
	short embedTAT = 0;
	short microTAT = 0;
	short routeTAT = 0;
	short finalTAT = 0;
	int value5 = 0;
	long caseID = 0;
	String caseNo = "";
	String facility = "";
	String specialty = "";
	String subspecial = "";
	String procedure = "";
	String specimen = "";
	String status = "";
	String grossName = "";
	String grossFull = "";
	String embedName = "";
	String embedFull = "";
	String microName = "";
	String microFull = "";
	String routeName = "";
	String routeFull = "";
	String finalName = "";
	String finalFull = "";
	Calendar accessed = Calendar.getInstance();
	Calendar grossed = Calendar.getInstance();
	Calendar embeded = Calendar.getInstance();
	Calendar microed = Calendar.getInstance();
	Calendar routed = Calendar.getInstance();
	Calendar finaled = Calendar.getInstance();
}