package ca.powerj;

import java.util.ArrayList;
import java.util.Calendar;

class OCaseFinal {
	boolean hasError = false;
	boolean hasLN = false;
	boolean codeSpec = false; // Not molecular or FISH cases
	boolean needFrag = false;
	byte noFSSpec = 0;
	byte noSpec = 0;
	byte noSynop = 0;
	byte procID = 0;
	byte subID = 0;
	byte spyID = 0;
	short facID = 0;
	short noBlocks = 0;
	short noFSBlks = 0;
	short noFSSlds = 0;
	short noHE = 0;
	short noIHC = 0;
	short noMol = 0;
	short noSlides = 0;
	short noSS = 0;
	short grossID = 0;
	short embedID = 0;
	short microID = 0;
	short routeID = 0;
	short finalID = 0;
	short mainSpec = 0;
	short mainBlocks = 0;
	int value5 = 0;
	int grossTAT = 0;
	int embedTAT = 0;
	int microTAT = 0;
	int routeTAT = 0;
	int finalTAT = 0;
	long caseID = 0;
	double value1 = 0;
	double value2 = 0;
	double value3 = 0;
	double value4 = 0;
	String caseNo = "";
	String comment = "";
	String facName = "";
	String spyName = "";
	String subName = "";
	String procName = "";
	String specName = "";
	String grossName = "";
	String grossFull = "";
	String embedName = "";
	String embedFull = "";
	String microName = "";
	String microFull = "";
	String routeName = "";
	String routeFull = "";
	String finalName = "";
	String finalFull = "";
	Calendar accessed = Calendar.getInstance();
	Calendar grossed = Calendar.getInstance();
	Calendar embeded = Calendar.getInstance();
	Calendar microed = Calendar.getInstance();
	Calendar routed = Calendar.getInstance();
	Calendar scanned = Calendar.getInstance();
	Calendar finaled = Calendar.getInstance();
	ArrayList<OSpecFinal> lstSpecimens = new ArrayList<OSpecFinal>();
}